spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "admin"
    password: "admin123"
    url: jdbc:postgresql://localhost:5432/site-creation
